# Generated by ChatGPT-5

import json
import shutil
import os

# 输入文件路径
input_file = "build.json"

with open(input_file, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        try:
            data = json.loads(line)
            if data.get("emit") == "link":
                src = data["artifact"]
                dst = "./rustprog.a"  # 复制到当前目录并保留文件名
                shutil.copy(src, dst)
                print(f"type: {type(dst)} ")
                print(f"已复制: {src} → {dst} ")
        except json.JSONDecodeError as e:
            print(f"JSON 解析失败: {e}")
        except FileNotFoundError:
            print(f"找不到文件: {src}")
